# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='speakers',
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(to='core.Speaker', verbose_name='palestrante'),
        ),
    ]
